language: vim

before_script: |
  hg clone https://vim.googlecode.com/hg vim
  make -C ./vim
  git clone https://github.com/junegunn/vader.vim.git

script: |
  VIMRUNTIME=vim/runtime vim/src/vim -XNu <(cat << EOF
  filetype off
  set runtimepath+=vader.vim
  set runtimepath+=.
  filetype plugin on
  syntax enable
  set hidden
  EOF) -c 'Vader! test/*' >/dev/null
